name: Automated builds

on:
  push:
    branches:
      - '**'
    tags:
      # Run when pushing version tags, since otherwise it's impossible to
      # restart a successful build after pushing a tag
      - '*.*.*'
  pull_request:
    branches:
      - master

defaults:
  run:
    # This otherwise gets run under dash which does not support brace expansion
    shell: bash

jobs:
  build:
    name: Build on Ubuntu 20.04
    runs-on: ubuntu-latest
    container: robbert/docker-yabridge:focal
    steps:
      - uses: actions/checkout@v3
      # Needed for git-describe to do anything useful, the safe directory
      # workaround is needed for https://github.com/actions/runner/issues/2033
      - name: Fetch all git history
        run: |
          git config --global --add safe.directory /__w/vstbridge/vstbridge
          git fetch --force --prune --tags --unshallow
      - name: Install GTK3 (for vstbridgectl-gtk)
        run: |
          apt-get update
          apt-get install -y libgtk-3-dev
      - name: Build bridge binaries
        run: |
          mkdir -p /tmp/prefix
          export WINEPREFIX=/tmp/prefix

          # In this version we don't need to statically link libstdc++ since
          # Ubuntu 20.04 and similar distros will ship with a version that's
          # compatible with GCC 10, even if that's not the default GCC version
          meson setup build --buildtype=release --cross-file=cross-wine.conf --unity=on --unity-size=10000 -Dbitbridge=true
          ninja -C build
      - name: Build vstbridgectl
        run: make -C tools/vstbridgectl
      - name: Strip debug symbols
        run: |
          strip build/libvstbridge{,-chainloader}-{clap,vst2,vst3}.so build/vstbridge-host{,-32}.exe.so
          strip tools/vstbridgectl/build/vstbridgectl tools/vstbridgectl/build/vstbridgectl-gtk
